title = "luizdepra"

theme = "coder"

languageCode = "pt-br"
defaultContentLanguage = "pt-br"
defaultContentLanguageInSubdir = true

paginate = 20
canonifyURLs = true

enableEmoji = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[markup.highlight]
style = "github-dark"
tabWidth = 4

[params]
author = "Luiz de Prá"
avatarURL = "images/avatar.jpg"
images = ["images/og_cover.png"]
description = "Site pessoal e blog de Luiz de Prá"
keywords = "blog,desenvolvedor,pessoal,software,python,c++,go,rust"
info = "Desenvolvedor de Software e Jogos"

dateFormat = "2006-01-02"

colorScheme = "dark"
hideColorSchemeToggle = true

customSCSS = ["scss/custom.scss"]

[params.goatCounter]
code = "luizdepra"

[params.utterances]
repo = "luizdepra/luizdepra.dev"
issueTerm = "pathname"
theme = "dark"

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/luizdepra/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 2
url = "https://twitter.com/luizdepra/"

[[params.social]]
name = "Twitter"
icon = "fa fa-mastodon fa-2x"
weight = 3
url = "https://mastodon.gamedev.place/@luizdepra"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/luizdepra/"

[[params.social]]
name = "RSS"
icon = "fa fa-rss-square fa-2x"
weight = 5
url = "/posts/index.xml"

[[menu.main]]
name = "Agora"
weight = 1
url = "agora/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[menu.main]]
name = "Usos"
weight = 3
url = "usos/"

[[menu.main]]
name = "Sobre"
weight = 4
url = "sobre/"
